### ISSUE TITLE
Detailed feedback San Joaquin and Riverside

### ISSUE THREAD

**Issue by albertkun** [ucla-lppi/report-generator#13]
Please review these PDFs for extra details

### San Joaquin
https://drive.google.com/file/d/14zGya7hGvXRVmEfoK0ossbPoSnlddKm6/view?usp=drive_link

### Riverside
https://drive.google.com/file/d/1pac8iJiXM1FrQ4v__lxw91byJE8a7ib9/view?usp=drive_link

**Comment by ismara-fg** [comment]
Because we're now creating template language, I think this issue is now moot, and I think we can close it. We'll have to review all the factsheets once we're able to implement the template language anyway :')

**Comment by albertkun** [comment]
Good point @ismara-fg ! I've created a new issue for this: #17 !
