### ISSUE TITLE
Finalize Variables for Extreme Heat factsheets

### ISSUE THREAD

**Issue by albertkun** [ucla-lppi/report-generator#15]
Met on Friday 10/4 to discuss the final variables for the extreme heat factsheet!

**Comment by albertkun** [comment]
23 total counties
19 counties are at the 70% thresholds vs. white.
but 3 counties are being compared amongst all other populations
sacramento is compared at 50% vs. white

**Comment by alejandresam** [comment]
Finished fixing ACS neighborhood level columns nlw -> comp 
https://docs.google.com/spreadsheets/d/1LsAoUJ6JEl9uQOrPCIS1oNKcAdVzWVjACMGgatef-k4/edit?gid=1778580211#gid=1778580211

**Comment by alejandresam** [comment]
I also realized that I sent Albert the neighborhood tracts for the **70+ lat, 70+ nlw, and other** based on these conditions only. I am not sure if we would like to get the **50+ lat, 50+ nlw, and other** for Sacramento + any future county. How would we condition these maps based on the neighborhoods?

**Comment by albertkun** [comment]
@alejandresam if the census tract has it, then ideally you can use the new categorization column! If not, then you'd have to either run the code to generate that for the census tracts. Let me know if that makes sense!

**Comment by alejandresam** [comment]
Finished adding comp columns and sending Albert the census tract data

**Comment by albertkun** [comment]
Yasss, thank you!!
